### ISSUE TITLE
Non-Default Language Folders

### ISSUE THREAD

**Issue by hokkqi** [buhrmi/trnsltr#14]
From the looks of it, trnsltr isn't bound to any programming language, i.e. even Typescript Projects could use it, so would it be possible to make the Folder containing the Language Files, customizable? 

I, for example, put my Language files into `langs/<language code>.yml` instead of `config/locales`

**Comment by buhrmi** [comment]
hey there. I stopped working on this project. Check out https://gitlocalize.com, it offers the same functionality (also free)
